# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Delegation API production build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install node_modules
        run: yarn
      - name: Install plugins module
        run: yarn init-plugins
      - name: Build
        run: |
          yarn build

          cp package.json dist/apps/delegation-api

          cp yarn.lock dist/apps/delegation-api

          cp apps/delegation-api/src/config/*  dist/apps/delegation-api/config
      - name: Lint
        run: yarn lint
